addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.2.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"      % "1.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.13")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.4.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix" % "0.9.12")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.9.2")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "2.0.0")
