addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.2.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"      % "1.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.13")
//addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.4.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix" % "0.9.12")
